### ISSUE TITLE
[js] не скрывается блока портфеля при повтором нажатии на ссылку

### ISSUE THREAD

**Issue by Mazian** [FantLab/FantLab-pub#24]
Нагдядно суть проблемки

![p-link_bug](https://user-images.githubusercontent.com/5379752/45878830-286ba280-bdab-11e8-84b7-3120a17794c0.gif)

Связано с тем кроме обработчика нажатия на ссылку и которая выводит блок
```
    $("#pf-link").click(function() {
        $(".portfolio").toggle();
    });
```

Существует еще скрипт, что закрывает этот блок при клике в любое место.
```
    // закрытие блока портфеля по клику в любое место экрана
    $(document).on('mouseup', function(e) {
        var container = $(".portfolio");
        if (!container.is(e.target) && container.has(e.target).length === 0)
        {
            container.hide();
        }
    });
```

И получается что при клике на ссылку при открытом блоке вначале выполняется закрытие блока (как клик по любому месту экрана), а потом сразу отрабатывает `$("#pf-link").click(function() { .. }`

Вероятно в функцию `$(document).on('mouseup', function(e) { ... }` надо поставить какую-либо проверку, но непонятно как...

**Comment by iris-the-fox** [comment]
```
$(document).on('mouseup', function(e) {
  var container = $(".portfolio");
  var pfLink = $(e.target).closest("#pf-link")
  if (!container.is(e.target) && container.has(e.target).length === 0 && pfLink.length==0)
  {
    container.hide();
  }
});
```

**Comment by Mazian** [comment]
Спасибо. Отличное решение!
Внедрил на сайт.
